### ISSUE TITLE
'type' object is not subscriptable

### ISSUE THREAD

**Issue by sujanme25** [ogrnz/feval#4]
<ipython-input-278-a8d2f4cc6640> in <module>
     96     kernel_kwargs: Optional[dict] = None,
     97     alpha: float = 0.05,
---> 98 ) -> tuple[float, float, float]:
     99     """
    100     Test of Equal Conditional Predictive Ability by Giacomini and White (2006).

TypeError: 'type' object is not subscriptable

**Comment by ogrnz** [comment]
Hi!
What version of python are you using?
Native type hints are supported from python 3.9, which is a requirement for this package. 

I will make this clearer in the readme. Also, I might add __future__ type annotations which should solve the issue for you. I'd still suggest updating your python version if it's a possibility for you.
